### ISSUE TITLE
How do I Fix This?

### ISSUE THREAD

**Issue by JadenNeil2020** [NSG650/BugCheckHack#12]
When I tried to create a service using the BugCheckHack.sys, This happens:

<img width="286" alt="image" src="https://github.com/NSG650/BugCheckHack/assets/75154286/c7af994c-58d7-40cb-8e0d-3089e419ab01">

Can anyone help me how to fix this?

**Comment by NSG650** [comment]
what is the command you are passing?

**Comment by JadenNeil2020** [comment]
Idk but when i switched to the 2.0 one and clicked run service it says Failed to download the symbols even tough I'm connected to the Internet and I'm on test mode in Windows Server 2022

**Comment by JadenNeil2020** [comment]
hello NSG?

**Comment by JadenNeil2020** [comment]
r u there?

**Comment by JadenNeil2020** [comment]
Nvm
