### ISSUE TITLE
Bugcheck 50 on startup

### ISSUE THREAD

**Issue by MattDevsWasTaken** [NSG650/BugCheckHack#3]
Hi, after I added it to the service, every time Windows starts up I get bugcheck 50. 
Windows 11 22000.193

**Comment by NSG650** [comment]
![image](https://user-images.githubusercontent.com/51860844/135075830-02491591-82f3-44b7-94e3-25d8b1f2877f.png)
to get rid of BugCheckHack now. Boot into safemode and then login open up cmd as administrator and run
```
sc delete BugCheckHack
```
 I am going to post the Windows 11 binary soon
