### ISSUE TITLE
A universal version

### ISSUE THREAD

**Issue by michelle1574** [NSG650/BugCheckHack#5]
I see that you are releasing versions for some builds. Maybe something about a universal version that works on all Windows builds?

**Comment by NSG650** [comment]
Hi sorry for replying so late.
I had an idea of such a version where I would use PDB symbols instead of disassembling functions and getting the function address. I would try to implement it soon.

**Comment by itsvic-dev** [comment]
soom&trade;

**Comment by NSG650** [comment]
Done!
