### ISSUE TITLE
Doesn't work on Win10 2004

### ISSUE THREAD

**Issue by masckmaster2007** [NSG650/BugCheckHack#8]
![image](https://user-images.githubusercontent.com/63162857/221366032-327daaa0-bc2f-49c3-9ab1-4245802a371e.png)
Tutorial used : https://www.youtube.com/watch?v=usmsmNkOVqQ

**Comment by NSG650** [comment]
Sorry for the extremely late reply, I was busy with exams. BugCheckHack does not work in any other language as it compares the english string texts. So try using it again with English US instead.
